description: The NikeITDepartmentCollector component is designed to collect information
  about personas in the Nike company's IT department. This component connects to the
  Nike Company API using the GET method and retrieves data about employees working
  in the IT Department. After receiving the API response, this component parses the
  response to extract relevant information such as names and emails of the personas
  in that department.
name: NikeITDepartmentCollector
parameters:
  api_endpoint: https://api.nike.com/it_department_personas
