description: Receives the extracted name and email list from the NameEmailExtractor
  component, connects to Salesforce using the provided SalesforceCredentials, and
  uploads the data. Finally, returns a status message with the indication whether
  data sending was successful or not.
name: SalesforceDataSender
parameters:
  salesforce_credentials: salesforce_credentials.yml
